### ISSUE TITLE
OpenOCD fails to place breakpoint on main

### ISSUE THREAD

**Issue by mellowcandle** [foss-for-synopsys-dwc-arc-processors/openocd#15]
OpenOCD fails to place breakpoint on main.
Environment:

AXS103, HS38 debugging through USB interface of FPGA.
Synopsys Eclipse debugging through OpenOCD

Console output:

Open On-Chip Debugger 0.9.0-dev-g8a252b3 (2015-06-08-13:44)
Licensed under GNU GPL v2
For bug reports, read
    http://openocd.sourceforge.net/doc/doxygen/bugs.html
debug_level: 0
adapter speed: 10000 kHz
target state: halted
target state: halted
Error: Unable to set 32bit breakpoint at address 20000078 - check that memory is read/writable
Error: Unable to set 32bit breakpoint at address 20000078 - check that memory is read/writable
Assertion failed!

Program: C:\arc_gnu\bin\openocd.exe
File: arc_mem.c, Line 34

Expression: addr_end >= addr

This application has requested the Runtime to terminate it in an unusual way.
Please contact the application's support team for more information.

**Comment by anthony-kolesov** [comment]
Sorry for late response - is this still a problem? I've tried this a few days back and I didn't had any issues with setting a breakpoint at 0x2z aperture. Currently OpenOCD doesn't support HS38 in AXS103, because it has L2$ which is not supported, although it shouldn't cause a problem when inserting breakpoints.

If you still have a problem, could you run OpenOCD with option `-d3 -l <logfile>` and then attach logfile and list commands that are done on the GDB side.
